[router]
# RX: '..00' ports
# TX: '..01' ports  

rx_cmd_sock_addr = "0.0.0.0:8000"

rx_app_sock_addr = "127.0.0.1:4000"
tx_app_sock_addr = "127.0.0.1:4001"

multicast_ip = "239.255.0.1"
multicast_port = 5000


[mls]
node_id = "node9"
credential_type = "ed25519"
update_interval_secs = 9999999999 #Set arbitrarily large so that there are no updates sent during testing
