[router]
# RX: '..00' ports
# TX: '..01' ports  

rx_cmd_sock_addr = "0.0.0.0:8000"

rx_app_sock_addr = "127.0.0.1:4000"
tx_app_sock_addr = "127.0.0.1:4001"

multicast_ip = "239.255.0.1"
multicast_port = 5000


[mls]
gcs_id = 1
node_id = 0
credential_type = "basic" #Valid options are "basic" and "ed25519" 
update_interval_secs = 10 #Set arbitrarily large to make sure no updates sent during testing