# version: "3.9"
services:
  node2:
    build:
      context: ..
      dockerfile: docker-test/Dockerfile
      args:
        NODE_NAME: node2
        NODE_IP: 10.10.0.2
        NODE_ID: 2
    container_name: node2
    hostname: node2
    environment:
        NODE_NAME: node2
        NODE_IP: 10.10.0.2
        NODE_ID: 2
    tty: true